version: '3'
services: 
    database:
        image: 'mongo'
        container_name: 'mongo-express'
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE=express
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
            #ME_CONFIG_MONGODB_ADMINUSERNAME: root
            #ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    cache:
        image: 'redis:6.0.6-alpine'
        ports: 
            - 6379:6379